import type { Metadata, NextPage } from 'next'
import { DM_Sans } from 'next/font/google'
import { PropsWithChildren } from 'react';
import './globals.css'
import Hero from '@/features/root/Hero';
import Footer from '@/features/root/Footer';

const inter = DM_Sans({ subsets: ['latin'] });

const RootLayout: NextPage<PropsWithChildren> = ({ children }) => {
    
    return (
        <html lang='en'>
            <body className={inter.className}>
                <div className='flex flex-col min-h-screen bg-gradient-to-tr text-white from-slate-950 to-slate-500'>
                    <div className='flex flex-col flex-grow w-full mx-auto'>
                        <Hero />
                        {children}
                    </div>
                    <Footer />
                </div>            
            </body>
        </html>
    );
}

export default RootLayout



export const metadata: Metadata = {
    title: 'Animation App',
    description: 'Generated by create next app',
}